name: Deploy y Build en Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: to github pages
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" 

      - name: Packeges
        run: npm install

      - name: Bundle
        run: npm run build
